export const modules = [
  { name: "Accélération G", file: "acceleration-g" },
  { name: "Force de Newton", file: "force-newton" },
  { name: "Temps Relatif", file: "temps-relatif" },
  { name: "Historique", file: "historique" },
  { name: "Orientation", file: "orientation" },
  { name: "Énergie", file: "energie" },
  { name: "Température", file: "temperature" },
  { name: "Humidité", file: "humidite" },
  { name: "Distance", file: "distance" },
  { name: "GPS Précision", file: "gps-precision" },
  { name: "Vitesse RTX", file: "rtx-vitesse" },
  { name: "Inertiel", file: "inertiel" },
  { name: "Gradient Solaire", file: "solaire-gradient" },
  { name: "Phase Lunaire", file: "lunaire-phase" },
  { name: "Boussole Lunaire", file: "boussole-lunaire" },
  { name: "Boussole Sidérale", file: "boussole-sidérale" },
  { name: "Boussole Fusion", file: "boussole-fusion" },
  { name: "Mobile Panel", file: "mobile-panel" },
  { name: "Intro Cosmique", file: "intro-cosmique" }
];
